/*
 * Copyright (C) 2025  Tetex7
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * !!WARNING!!
 * AUTO-GENERATED CONFIG HEADER
 * Project: glen_elf_tool
 * Generated by CMake on 11-18-2025(21:52:36)
 * DO NOT EDIT THIS FILE DIRECTLY.
 */

/*
 * Git Commit: 
 * on Branch:  
 */


#pragma once

#ifndef GLEN_ELF_TOOL_CONFIG_H
#define GLEN_ELF_TOOL_CONFIG_H

#define GLEN_ELF_TOOL_SYSTEM_BUILT_FOR "Linux"

#define GLEN_ELF_TOOL_CONFIG_DEBUG
#define GLEN_ELF_TOOL_CONFIG_STR_VERSION "1.0.0"
#define GLEN_ELF_TOOL_CONFIG_VERSION_MAJOR 1
#define GLEN_ELF_TOOL_CONFIG_VERSION_MINOR 0
#define GLEN_ELF_TOOL_CONFIG_VERSION_PATCH 0


#define GLEN_ELF_TOOL_GIT_COMMIT_HASH ""
#define GLEN_ELF_TOOL_GIT_COMMIT_HASH_INT 0x
#define GLEN_ELF_TOOL_GIT_BRANCH_NAME ""

#define GLEN_ELF_TOOL_C_COMPILER_ID "GNU"
#if defined(__clang__)
#   define GLEN_ELF_TOOL_ON_CLANG
#   define GLEN_ELF_TOOL_C_COMPILER "CLANG"
#elif defined(__GNUC__)
#   define GLEN_ELF_TOOL_ON_GCC
#   define GLEN_ELF_TOOL_C_COMPILER "GCC"
#elif defined(_MSC_VER)
#   define GLEN_ELF_TOOL_ON_MSVC
#   define GLEN_ELF_TOOL_C_COMPILER "MSVC"
#endif

#if defined(__unix__) || defined(__unix) || defined(__APPLE__)
#   define GLEN_ELF_TOOL_ON_UNIX
#elif defined(_WIN32)
#   define GLEN_ELF_TOOL_ON_WIN32
#endif

#endif //LIBSAFETYNET_CONFIG_H
